import imageSrc from "../assets/restaurant/pizza.jpg";
const restaurantData = [
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
  {
    imageSrc,
    name: "restaurant 1",
    address: "Lima av. Javier Prado",
    country: "8rTBsf4ObQ",
    state: "nGG9q37Dp5",
    zipCode: "+ 51",
    category: "Gourmet",
    rating: 4,
    reviewCount: 90,
  },
];

export default restaurantData;
